### PR TITLE
Merging back latest Belgium vaccination survey

### PR DESCRIPTION
**Pull request by InfectieradarBE**

### CODE REVIEW

**Comment by phev8** [comment]
@danielapaolotti can you try merging this PR please?

**Comment by danielapaolotti** [comment]
Ok, it looks good. I approve the changes :)

**Comment by danielapaolotti** [comment]
But you need to give me write access :)

**Comment by phev8** [comment]
I added you the rights to manage pull request, maybe you need to login again, can you try please?

**Pull request merged**
